new

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,102 +14,82 @@ jobs:
   release:
     name: build and release
     runs-on: ubuntu-latest
-    env:
-      DIST_DIR: '${{ github.workspace }}/dist'
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set version
-        id: set_version
-        run: |
-          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-            VERSION=${{ github.event.inputs.tag }}
-          else
-            VERSION=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
-          fi
-
-          # 检查版本是否成功获取
-          if [ -z "${VERSION}" ]; then
-            echo "Error: VERSION could not be determined" >&2
-            exit 1
-          fi
-
-          # 打印获取到的版本号并将其存入环境变量
-          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-          echo "Version set to: ${VERSION}"
-
-      - name: Setup FreeBSD environment
+      - name: Setup and Build on FreeBSD
         uses: vmactions/freebsd-vm@v1
         with:
           usesh: true
           release: 14.1
           prepare: |
-            pkg install -y wget curl git go121 gcc bash jq node
+            pkg install -y wget curl git go121 gcc bash jq node zip tar
             ln -s /usr/local/bin/go121 /usr/local/bin/go
+          run: |
+            # Set version
+            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+              VERSION=${{ github.event.inputs.tag }}
+            else
+              VERSION=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
+            fi
 
-      - name: Build the project
-        run: |
-          version_num=${{ env.VERSION }}
-          version_num=${version_num#v}
+            # 检查版本是否成功获取
+            if [ -z "${VERSION}" ]; then
+              echo "Error: VERSION could not be determined" >&2
+              exit 1
+            fi
 
-          if git ls-remote --tags https://github.com/naiba/nezha | grep "refs/tags/${{ env.VERSION }}"; then
-            git clone -b ${{ env.VERSION }} https://github.com/naiba/nezha
-          else
-            echo "Error: Tag ${{ env.VERSION }} not found in naiba/nezha repository" && exit 1
-          fi
+            echo "VERSION=${VERSION}" >> $GITHUB_ENV
+            echo "Version set to: ${VERSION}"
 
-          rm -rf nezha/pkg/geoip/geoip.db
-          wget -qO nezha/pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${{ secrets.IPINFO_TOKEN }}
-          cd nezha/cmd/dashboard
-          go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${version_num}"
-          file dashboard
+            # Build the project
+            version_num=${VERSION#v}
 
-      - name: Fix dist
-        run: |
-          mkdir -p "${DIST_DIR}"
-          cp -rf "nezha/resource" "${DIST_DIR}"
-          rm "${DIST_DIR}/resource/resource.go"
-          mv -f "nezha/cmd/dashboard/dashboard" "${DIST_DIR}/nezha-dashboard"
+            if git ls-remote --tags https://github.com/naiba/nezha | grep -q "refs/tags/${VERSION}"; then
+              git clone -b ${VERSION} https://github.com/naiba/nezha
+            else
+              echo "Error: Tag ${VERSION} not found in naiba/nezha repository" && exit 1
+            fi
 
-      - name: Prepare config.yaml
-        run: |
-          mkdir -p "${DIST_DIR}/data"
-          cp -rf nezha/script/config.yaml "${DIST_DIR}/data/config.yaml"
+            rm -rf nezha/pkg/geoip/geoip.db
+            wget -qO nezha/pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${{ secrets.IPINFO_TOKEN }}
+            cd nezha/cmd/dashboard
+            go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${version_num}"
+            file dashboard
 
-      - name: Compress dist files
-        run: |
-          echo "111Checking DIST_DIR before compression:"
+            # Prepare dist
+            mkdir -p /tmp/dist
+            cp -rf ../../resource /tmp/dist
+            rm /tmp/dist/resource/resource.go
+            mv dashboard /tmp/dist/nezha-dashboard
 
-          TEMP_DIR=$(mktemp -d)
-          cp -R "${DIST_DIR}/." "$TEMP_DIR"  # 确保复制所有文件，包括隐藏文件
-          rm -rf "${DIST_DIR}"/*
-          ls -l "${DIST_DIR}"
-          echo "Checking TEMP_DIR after copying from DIST_DIR:"
-          ls -l "$TEMP_DIR"
-    
-          cd "$TEMP_DIR"
-          zip -qr "${DIST_DIR}/nezha-dashboard.zip" .  # 使用 -q 静默模式
-          tar -czf "${DIST_DIR}/nezha-dashboard.tar.gz" .
+            # Prepare config.yaml
+            mkdir -p /tmp/dist/data
+            cp -rf ../../script/config.yaml /tmp/dist/data/config.yaml
 
-          echo "Files in DIST_DIR after compression:"
-          ls -l "${DIST_DIR}"
+            # Compress dist files
+            cd /tmp/dist
+            zip -qr nezha-dashboard.zip .
+            tar -czf nezha-dashboard.tar.gz .
 
-      - name: Check DIST_DIR
-        run: |
-          echo "Checking contents of DIST_DIR:"
-          ls -l "${DIST_DIR}"
+            # Move artifacts to a location accessible outside the VM
+            mkdir -p /freebsd_artifacts
+            mv nezha-dashboard.zip nezha-dashboard.tar.gz /freebsd_artifacts/
+
+            # Check the file type of the built binary
+            file /tmp/dist/nezha-dashboard
 
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: nezha-freebsd
-          path: ${{ env.DIST_DIR }}/*
+          path: /freebsd_artifacts/*
 
       - name: Release
         uses: ncipollo/release-action@v1
         with:
           tag: ${{ env.VERSION }}
-          artifacts: "${{ env.DIST_DIR }}/*.zip, ${{ env.DIST_DIR }}/*.tar.gz"
+          artifacts: "/freebsd_artifacts/*.zip,/freebsd_artifacts/*.tar.gz"
           generateReleaseNotes: true
           makeLatest: legacy
           omitBody: false
