new

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,9 +1,8 @@
 name: Build and Release
-
 on:
   push:
     tags:
-      - "v*"
+      - 'v*'
   workflow_dispatch:
     inputs:
       tag:
@@ -12,12 +11,14 @@ on:
         default: 'v0.19.20'
 
 jobs:
-  set_version:
-    name: Set Version
+  release:
+    name: build and release
     runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.set_version.outputs.VERSION }}
+    env:
+      DIST_DIR: '${{ github.workspace }}/dist'
     steps:
+      - uses: actions/checkout@v4
+
       - name: Set version
         id: set_version
         run: |
@@ -26,35 +27,16 @@ jobs:
           else
             VERSION=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
           fi
+
+          # 检查版本是否成功获取
           if [ -z "${VERSION}" ]; then
             echo "Error: VERSION could not be determined" >&2
             exit 1
           fi
-          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
+
+          # 打印获取到的版本号并将其存入环境变量
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
           echo "Version set to: ${VERSION}"
-
-  freebsd_build:
-    name: Build for FreeBSD
-    runs-on: ubuntu-latest
-    needs: set_version
-    env:
-      DIST_DIR: '${{ github.workspace }}/dist'
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Checkout nezha repository
-        uses: actions/checkout@v4
-        with:
-          repository: naiba/nezha
-          ref: ${{ needs.set_version.outputs.version }}
-          path: nezha
-
-      - name: Fetch IPInfo GeoIP Database
-        env:
-          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
-        run: |
-          rm -rf nezha/pkg/geoip/geoip.db
-          wget -qO nezha/pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}
 
       - name: Cache Go modules
         uses: actions/cache@v3
@@ -72,124 +54,71 @@ jobs:
           usesh: true
           release: 14.1
           prepare: |
-            pkg install -y wget curl git go121 gcc bash jq node zip
+            pkg install -y wget curl git go121 gcc bash jq node
             ln -s /usr/local/bin/go121 /usr/local/bin/go
 
       - name: Build the project
         run: |
-          version_num=${{ needs.set_version.outputs.version }}
+          version_num=${{ env.VERSION }}
           version_num=${version_num#v}
+
+          if git ls-remote --tags https://github.com/naiba/nezha | grep "refs/tags/${{ env.VERSION }}"; then
+            git clone -b ${{ env.VERSION }} https://github.com/naiba/nezha
+          else
+            echo "Error: Tag ${{ env.VERSION }} not found in naiba/nezha repository" && exit 1
+          fi
+
+          rm -rf nezha/pkg/geoip/geoip.db
+          wget -qO nezha/pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${{ secrets.IPINFO_TOKEN }}
           cd nezha/cmd/dashboard
           go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${version_num}"
 
-      - name: Prepare dist directory
+      - name: Fix dist
         run: |
           mkdir -p "${DIST_DIR}"
           cp -rf "nezha/resource" "${DIST_DIR}"
           rm "${DIST_DIR}/resource/resource.go"
           mv -f "nezha/cmd/dashboard/dashboard" "${DIST_DIR}/nezha-dashboard"
+
+      - name: Prepare config.yaml
+        run: |
           mkdir -p "${DIST_DIR}/data"
           cp -rf nezha/script/config.yaml "${DIST_DIR}/data/config.yaml"
 
       - name: Compress dist files
         run: |
+          echo "111Checking DIST_DIR before compression:"
+
           TEMP_DIR=$(mktemp -d)
-          cp -R "${DIST_DIR}/." "$TEMP_DIR"
+          cp -R "${DIST_DIR}/." "$TEMP_DIR"  # 确保复制所有文件，包括隐藏文件
           rm -rf "${DIST_DIR}"/*
+          ls -l "${DIST_DIR}"
+          echo "Checking TEMP_DIR after copying from DIST_DIR:"
+          ls -l "$TEMP_DIR"
+    
           cd "$TEMP_DIR"
-          zip -qr "${DIST_DIR}/dashboard-freebsd-amd64.zip" .
-          tar -czf "${DIST_DIR}/dashboard-freebsd-amd64.tar.gz" .
+          zip -qr "${DIST_DIR}/nezha-dashboard.zip" .  # 使用 -q 静默模式
+          tar -czf "${DIST_DIR}/nezha-dashboard.tar.gz" .
 
-      - name: Upload artifact for FreeBSD
-        uses: actions/upload-artifact@v4
-        with:
-          name: dashboard-freebsd-amd64
-          path: |
-            ${{ env.DIST_DIR }}/*
+          echo "Files in DIST_DIR after compression:"
+          ls -l "${DIST_DIR}"
 
-  build:
-    strategy:
-      fail-fast: true
-      matrix:
-        goos: [linux, windows]
-        goarch: [amd64]
-        include:
-          - goos: linux
-            goarch: s390x
-          - goos: linux
-            goarch: arm64
-           
-    name: Build artifacts ${{ matrix.goos }}-${{ matrix.goarch }}
-    runs-on: ubuntu-latest
-    needs: set_version
-    env:
-      GOOS: ${{ matrix.goos }}
-      GOARCH: ${{ matrix.goarch }}
-      DIST_DIR: '${{ github.workspace }}/dist'
-
-    steps:
-      - name: Checkout nezha repository
-        uses: actions/checkout@v4
-        with:
-          repository: naiba/nezha
-          ref: ${{ needs.set_version.outputs.version }}
-          path: nezha
-
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: "1.21.x"
-
-      - name: Install dependencies
+      - name: Check DIST_DIR
         run: |
-          sudo apt-get update
-          sudo apt-get install -y zip
+          echo "Checking contents of DIST_DIR:"
+          ls -l "${DIST_DIR}"
 
-      - name: Fetch IPInfo GeoIP Database
-        env:
-          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
-        run: |
-          rm -rf nezha/pkg/geoip/geoip.db
-          wget -qO nezha/pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}
-
-      - name: Ensure Git Repository
-        run: |
-          git init
-          git remote add origin https://github.com/naiba/nezha.git
-          git fetch --all
-          git checkout ${{ needs.set_version.outputs.version }}
-
-      - name: Build with GoReleaser
-        uses: goreleaser/goreleaser-action@v6
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
         with:
-          version: '~> v2'
-          args: build --single-target --clean --skip=validate
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
-
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: dashboard-${{ matrix.goos }}-${{ matrix.goarch }}
-          path: |
-            ./dist/*/*
-
-  release:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
-    needs: [freebsd_build, build]
-    name: Release
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: ./assets
+          name: nezha-freebsd
+          path: ${{ env.DIST_DIR }}/*
 
       - name: Release
         uses: ncipollo/release-action@v1
         with:
-          tag: ${{ needs.set_version.outputs.version }}
-          artifacts: "assets/*/*.{zip,tar.gz}"
+          tag: ${{ env.VERSION }}
+          artifacts: "${{ env.DIST_DIR }}/*.zip, ${{ env.DIST_DIR }}/*.tar.gz"
           generateReleaseNotes: true
           makeLatest: legacy
           omitBody: false
